runtime: nodejs20
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:
  - url: /_next/static/
    static_dir: .next/static
  - url: /static/
    static_dir: public/static
  - url: /.*
    script: auto
