import { Inter as FontSans } from "next/font/google"
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Godentist Smart Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">   
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="apple-mobile-web-app-status-bar" content="#FFE1C4" />
        {/* add */}
        <link rel='manifest' href='/manifest.json' />
        <meta name="theme-color" content="#2766EC" />
        <title>{metadata.title}</title>
      </head>
      <body className={fontSans.className}>{children}</body>
    </html>
  );
}
